### PR TITLE
melee state and animation

### PR DESCRIPTION
**Pull request by michellegramolini**
PR checklist:

I double checked that in the Unity project (all must be checked before merge)
- [x] There are no console errors.
- [x] My test Scene(s) work as expected.
- [x] I did not push any changes to Scenes I do not own.

PR Description:

- added a basic melee attack state and configured it on the player.
- hooked up basic attack animation
- configured only certain frames to deal damage
- updated player prefab
- created basic debug enemy

Screenshot 2023-06-19 at 10 18 32 PM
Screenshot 2023-06-19 at 10 19 24 PM

Trello ticket (Optional, but might provide good flavor for larger changes):

### CODE REVIEW

**Review by snowstriker — COMMENTED** [review]
Something similar happens with jump too I noticed, but while you're attacking if you hit a diff direction strange behavior happens.

**Comment by michellegramolini** [comment]
> Something similar happens with jump too I noticed, but while you're attacking if you hit a diff direction strange behavior happens.

lol can you be more specific? im mashing all the directions and attacking and jumping and it all looks fine to me.

**Comment by michellegramolini** [comment]
> 

the jump i will refine separately.

**Comment by snowstriker** [comment]
Seems fixed!

**Review by snowstriker — APPROVED** [review]

**Pull request merged**
