### PR TITLE
Spritz prefab

### PR DESCRIPTION
**Pull request by snowstriker**
PR checklist:

I double checked that in the Unity project (all must be checked before merge)
- [x] There are no console errors.
- [x] My test Scene(s) work as expected.
- [x] I did not push any changes to Scenes I do not own.

PR Description:

Trello ticket (Optional, but might provide good flavor for larger changes): 
https://trello.com/c/SxdqRVaA

Created Spritz prefab, with sheet in the Sprites folder, animations in the Animations / Spritz folder.

Moving the collider as well in the animation was intentional.

To test the animations, double click on the Spritz prefab in the Prefabs folder, click on its Sprite, then go to Animation console, and select a hop animation from the drop down and click play.

### CODE REVIEW

**Comment by snowstriker** [comment]
I realize now I moved the collider in animation, but what I actually wanted to move was whatever the hurtbox ends up being, maybe that won't be the collider. Can revisit whenever implementation is understood more.

**Review by michellegramolini — APPROVED** [review]

**Comment by michellegramolini** [comment]
> I realize now I moved the collider in animation, but what I actually wanted to move was whatever the hurtbox and hitbox end up being, maybe that won't be the collider. Can revisit whenever implementation is understood more.

the player is detecting a layer called "Enemy" that will have to be assigned to enemy prefabs, that layer is detected via the enemy's collider. (might also need a rigidbody, a kinematic one. actually, let me check your branch!

**Review by michellegramolini — APPROVED** [review]
just gonna check the prefab! i already reviewed

**Comment by Chufted** [comment]
Nick showed me some of this in person but I took a look at the prefab and animation and looks good to me 👍

**Review by Chufted — APPROVED** [review]

**Pull request merged**
